id: "hifigan"

#################################################
# Task configuration
#################################################

task:
    _name: "Vocoder"
    network:
        acoustic_model:
            _name: "HifiGANGenerator"
            upsample_rates: [5, 5, 4, 3]
            upsample_kernel_sizes: [11, 11, 9, 7]
            upsample_initial_channel: 512
            resblock_kernel_sizes: [3, 7, 11]
            resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
        discriminator:
            _name: 'HifiGANDiscriminator'

#################################################
# Trainer configuration
#################################################

# Basic hyperparameters
save_checkpoint_dir: "egs/ljspeech/voc/checkpoints/hifigan"
pretrain_checkpoint_path: ""
restore_checkpoint_path: ""
resume_training: True
training_steps: 2000000
iters_per_checkpoint: 50000
seed: 1234

# CuDNN configuration
cudnn:
    enabled: True
    benchmark: True

# Specific trainer hyperparameters
trainer:
    _name: 'HifiGANTrainer'
    sample_lengths: 21000
    stft_loss_supervised_step: 0
    lambda_fm: 2
    lambda_mel: 45

optimizer:
    _default:
        _name: "AdamW"
        learning_rate: 2e-4
        betas: [0.8, 0.99]
        eps: 1e-8
        weight_decay: 0.0
    
dataloader:
    batch_size: 16
    num_workers: 4

dataset:
    _name: 'AudioDataset'
    id_list: "/data/hhguo/corpus/ljspeech/train_tts.list"
    samplerate: 24000
    feature: ['mel', 'wav']
    feature_path: [
        '/data/hhguo/corpus/ljspeech/mel/{}.npy',
        '/data/hhguo/corpus/ljspeech/wav_24k/{}.wav',
    ]
    dimension: [80, 1]
    frameshift: [300, 1]
    padding_value: [-4, 0]
    pre_load: True
    segment_length: 24000 # samples

lr_scheduler:
    _name: "ExponentialDecayLRScheduler"
    warmup_steps: 200000
    decay_learning_rate: 0.5
    final_learning_rate: 1e-5

# Only for Multi-GPU Training
distributed:
    dist_backend: "nccl"
    dist_url: "tcp://localhost:54321"

#################################################
# Infer configuration
#################################################

save_features: [['wav', '.wav', 24000]]
